chore(#1575): Provide pdf api url from the env variables
IntersectMBO/govtool pull request #1593
Opened 2024-07-18 10:32 UTC by MSzalowski

## List of changes

- Add PDF_API_URL to the frontend config

## Checklist

- [related issue](https://github.com/IntersectMBO/govtool/issues/1575)
- [x] My changes generate no new warnings
- [x] My code follows the [style guidelines](https://github.com/IntersectMBO/govtool/tree/main/docs/style-guides) of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [changelog](https://github.com/IntersectMBO/govtool/blob/main/CHANGELOG.md)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-07-18 10:40 UTC, teske00 approved these changes
Passing the API URL to the PDF package looks fine

2024-07-18 12:07 UTC, placek requested changes

2024-07-18 12:07 UTC, placek commented on scripts/govtool/config/templates/docker-compose.yml.tpl
> +      - "traefik.http.middlewares.frontend-csp.headers.contentSecurityPolicy=default-src 'self'; img-src *.usersnap.com https://www.googletagmanager.com 'self' data:; script-src 'unsafe-inline' *.use
You have to declare that here:
https://github.com/IntersectMBO/govtool/blob/a554c459e2cd4e759275f4ee40fbb03282d409c9/scripts/govtool/config.mk#L55

2024-07-19 12:38 UTC, placek approved these changes

2024-07-19 12:59 UTC, merged

2024-07-23 08:45 UTC, bosko-m commented
So this one is done @MSzalowski ?