Move and refactor allure report script
IntersectMBO/govtool pull request #1749
Opened 2024-08-16 07:06 UTC by kneerose

## List of changes

-  Move the allure report script file from base to tests/script
-  Update report script path on the backend and integration test
-  Update deprecated set-output to GITHUB_OUTPUT env

## Checklist

- [related issue](https://github.com/IntersectMBO/govtool/issues/)
- [x] My changes generate no new warnings
- [x] My code follows the [style guidelines](https://github.com/IntersectMBO/govtool/tree/main/docs/style-guides) of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [changelog](https://github.com/IntersectMBO/govtool/blob/main/CHANGELOG.md)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-08-16 08:17 UTC, mesudip requested changes

2024-08-16 08:17 UTC, mesudip commented on tests/scripts/generate_latest_report_redirect.sh
Let's move these files to .github/scripts instead

2024-08-16 08:41 UTC, kneerose commented on tests/scripts/generate_latest_report_redirect.sh
done

2024-08-20 12:38 UTC, bosko-m commented
@MSzalowski @Ryun1 Im not sure whether you noticed this one guys :)

2024-08-20 12:42 UTC, bosko-m commented
@mesudip Are 4 reviewers mandatory?

2024-09-03 04:29 UTC, mesudip approved these changes
Looks Good

2024-09-03 04:30 UTC, merged