[#1951] Handle script based DReps
IntersectMBO/govtool pull request #2182
Opened 2024-10-18 09:27 UTC by jdyczka

## List of changes

- Handle script based DReps

## Checklist

- [related issue](https://github.com/IntersectMBO/govtool/issues/1951)
- [ x] My changes generate no new warnings
- [x] My code follows the [style guidelines](https://github.com/IntersectMBO/govtool/tree/main/docs/style-guides) of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [changelog](https://github.com/IntersectMBO/govtool/blob/main/CHANGELOG.md)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-10-18 09:39 UTC, Ryun1 commented on govtool/backend/src/VVA/API/Types.hs
> +      , dRepDrepId                 :: DRepHash
```suggestion
      , dRepID                 :: DRepHash
```

2024-10-18 11:31 UTC, MSzalowski commented on govtool/backend/src/VVA/API/Types.hs
> +      , dRepDrepId                 :: DRepHash
We are returning `drepId` not just `id`

2024-10-21 08:12 UTC, MSzalowski requested changes
If that is easier to depend on the `drep_hash.has_script` that is ok, but still for the script based Drep delegation certificate we need a script hash for such DRep, meaning, that we need to take this value.

So, having the `scriptHash` in a DRep should be just enough to establish that such DRep is script based

2024-10-21 08:12 UTC, MSzalowski commented on govtool/frontend/src/context/wallet.tsx
> +          targetDRep = DRep.new_script_hash(Ed25519KeyHash.from_bech32(target));
target should be:
```suggestion
          targetDRep = DRep.new_script_hash(ScriptHash.from_hex(target));
```

where `target` is the `scriptHash` of the script based DRep that is missing in the SQL.

I'll make the reference implementation of this and share you soon

2024-10-21 08:29 UTC, MSzalowski commented
> If that is easier to depend on the `drep_hash.has_script` that is ok, but still for the script based Drep delegation certificate we need a script hash for such DRep, meaning, that we need to take this value.
> 
> So, having the `scriptHash` in a DRep should be just enough to establish that such DRep is script based

I figured out that dRepId in our backend is already the scriptHash, so there is no need to update the SQL query - all good, just update pls that small change in wallet.tsx :saluting_face:

2024-10-21 11:59 UTC, MSzalowski approved these changes

2024-10-21 12:01 UTC, merged