Optimize sentry integration
IntersectMBO/govtool pull request #2449
Opened 2024-12-02 07:11 UTC by kneerose

## List of changes

- Make sentry initialize optional for frontend
- Introduce sentry enable flag 

## Checklist

- [related issue](https://github.com/IntersectMBO/govtool/issues/)
- [x] My changes generate no new warnings
- [x] My code follows the [style guidelines](https://github.com/IntersectMBO/govtool/tree/main/docs/style-guides) of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [changelog](https://github.com/IntersectMBO/govtool/blob/main/CHANGELOG.md)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-12-11 08:35 UTC, kneerose commented
@MSzalowski , could you please review this? Feel free to make any updates or changes as needed.

2025-01-02 07:11 UTC, mesudip commented
@MSzalowski , can you review and determine whether or not it is still relevant?

2025-01-03 10:35 UTC, MSzalowski approved these changes

2025-01-03 12:24 UTC, placek approved these changes

2025-01-20 10:38 UTC, MSzalowski commented
@kneerose Can we merge this PR?

2025-01-20 10:50 UTC, placek approved these changes

2025-01-23 04:01 UTC, mesudip requested changes

2025-01-23 04:01 UTC, mesudip commented on govtool/frontend/src/main.tsx
> +    dsn: import.meta.env.VITE_SENTRY_DSN,
If VITE_SENTRY_DSN is not present let's disable it by default.

2025-01-31 06:10 UTC, kneerose commented
@MSzalowski  can you review this again? also please look at this ticket
https://github.com/intersectMBO/govtool/issues/2776

2025-03-18 10:48 UTC, mesudip approved these changes
Looks good

2025-03-19 04:38 UTC, placek approved these changes

2026-07-16 09:48 UTC, closed without merging