[753] Chore; update copy on maintenance page
IntersectMBO/govtool pull request #754
Opened 2024-04-17 09:54 UTC by Ryun1

## List of changes

- Changed the copy on the maintenance page

## Checklist

- [related issue](https://github.com/IntersectMBO/govtool/issues/753)
- [x] My changes generate no new warnings
- [x] My code follows the [style guidelines](https://github.com/IntersectMBO/govtool/tree/main/docs/style-guides) of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [changelog](https://github.com/IntersectMBO/govtool/blob/main/CHANGELOG.md)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-04-18 08:15 UTC, MSzalowski requested changes

2024-04-18 08:15 UTC, MSzalowski commented on govtool/frontend/maintenance-page/index.html
> +          means that if the network gtes upgraded with new features
I believe there is a typo in `gtes`

2024-04-18 08:34 UTC, Ryun1 commented on govtool/frontend/maintenance-page/index.html
> +          means that if the network gtes upgraded with new features
```suggestion
          means that if the network gets upgraded with new features 
```

2024-04-18 08:36 UTC, Ryun1 commented on govtool/frontend/maintenance-page/index.html
> +          means that if the network gtes upgraded with new features
fixed !

2024-04-19 06:54 UTC, MSzalowski approved these changes

2024-04-19 19:20 UTC, merged